[tool.poetry]
name = "rv_ltl"
version = "0.1.0"
description = "Runtime Verification Linear Temporal Logic (RV-LTL) in Python"
authors = ["Shun Kashiwa <shunthedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.group.dev.dependencies]
pytest = ">=8"
black = { version = ">=24", python = ">=3.10" }
flake8 = { version = ">=7", python = ">=3.10" }
pep8-naming = { version = ">=0.14", python = ">=3.10" }
autopep8 = { version = ">=2", python = ">=3.10" }
pytest-cov = ">=5"
pdoc3 = { version = ">=0.11", python = ">=3.10" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
